const STACK = [
    "HTML",
    "CSS",
    "JS",
    "React",
    "Git",
    "Express.js",
    "mongoDB",
];

const exampleMovies = [
    {
      country: 'Country 1',
      director: 'Director 1',
      duration: 102,
      year: '2021',
      description: 'Description 1',
      image: 'https://basetop.ru/wp-content/uploads/2022/12/movies-2023-696x392.jpg',
      trailerLink: 'https://example.com/trailer1',
      thumbnail: 'https://example.com/thumbnail1.jpg',
      owner: 'user_id_1',
      movieId: 2,
      nameRU: '33 слова о дизайне',
      nameEN: 'Movie Name EN 1',
    },
    {
        country: 'Country 1',
        director: 'Director 1',
        duration: 102,
        year: '2021',
        description: 'Description 1',
        image: 'https://basetop.ru/wp-content/uploads/2022/12/movies-2023-696x392.jpg',
        trailerLink: 'https://example.com/trailer1',
        thumbnail: 'https://example.com/thumbnail1.jpg',
        owner: 'user_id_1',
        movieId: 3,
        nameRU: 'Киноальманах «100 лет дизайна»',
        nameEN: 'Movie Name EN 1',
      },
      {
        country: 'Country 1',
        director: 'Director 1',
        duration: 102,
        year: '2021',
        description: 'Description 1',
        image:  'https://basetop.ru/wp-content/uploads/2022/12/movies-2023-696x392.jpg',
        trailerLink: 'https://example.com/trailer1',
        thumbnail: 'https://example.com/thumbnail1.jpg',
        owner: 'user_id_1',
        movieId: 4,
        nameRU: 'В погоне за Бенкси',
        nameEN: 'Movie Name EN 1',
      },
      {
        country: 'Country 1',
        director: 'Director 1',
        duration: 102,
        year: '2021',
        description: 'Description 1',
        image: 'https://basetop.ru/wp-content/uploads/2022/05/2022-kino-filmy-.jpg',
        trailerLink: 'https://example.com/trailer1',
        thumbnail: 'https://example.com/thumbnail1.jpg',
        owner: 'user_id_1',
        movieId: 5,
        nameRU: 'Баския: Взрыв реальности',
        nameEN: 'Movie Name EN 1',
      },
      {
        country: 'Country 1',
        director: 'Director 1',
        duration: 102,
        year: '2021',
        description: 'Description 1',
        image: 'https://avatars.mds.yandex.net/get-kinopoisk-image/6201401/67c19114-3d37-4c76-92e6-ad1088a6f1f5/600x900',
        trailerLink: 'https://example.com/trailer1',
        thumbnail: 'https://example.com/thumbnail1.jpg',
        owner: 'user_id_1',
        movieId: 6,
        nameRU: 'Movie Name RU 1',
        nameEN: 'Movie Name EN 1',
      },
      {
        country: 'Country 1',
        director: 'Director 1',
        duration: 102,
        year: '2021',
        description: 'Description 1',
        image: 'https://basetop.ru/wp-content/uploads/2022/12/movies-2023-696x392.jpg',
        trailerLink: 'https://example.com/trailer1',
        thumbnail: 'https://example.com/thumbnail1.jpg',
        owner: 'user_id_1',
        movieId: 7,
        nameRU: 'Movie Name RU 1',
        nameEN: 'Movie Name EN 1',
      },
      {
        country: 'Country 1',
        director: 'Director 1',
        duration: 102,
        year: '2021',
        description: 'Description 1',
        image: 'https://basetop.ru/wp-content/uploads/2022/12/movies-2023-696x392.jpg',
        trailerLink: 'https://example.com/trailer1',
        thumbnail: 'https://example.com/thumbnail1.jpg',
        owner: 'user_id_1',
        movieId: 8,
        nameRU: 'Movie Name RU 1',
        nameEN: 'Movie Name EN 1',
      },
      {
        country: 'Country 1',
        director: 'Director 1',
        duration: 102,
        year: '2021',
        description: 'Description 1',
        image: 'https://basetop.ru/wp-content/uploads/2022/12/movies-2023-696x392.jpg',
        trailerLink: 'https://example.com/trailer1',
        thumbnail: 'https://example.com/thumbnail1.jpg',
        owner: 'user_id_1',
        movieId: 9,
        nameRU: 'Movie Name RU 1',
        nameEN: 'Movie Name EN 1',
      },
      {
        country: 'Country 1',
        director: 'Director 1',
        duration: 102,
        year: '2021',
        description: 'Description 1',
        image: 'https://basetop.ru/wp-content/uploads/2022/12/movies-2023-696x392.jpg',
        trailerLink: 'https://example.com/trailer1',
        thumbnail: 'https://example.com/thumbnail1.jpg',
        owner: 'user_id_1',
        movieId: 1,
        nameRU: 'Movie Name RU 1',
        nameEN: 'Movie Name EN 1',
      },
      {
        country: 'Country 1',
        director: 'Director 1',
        duration: 102,
        year: '2021',
        description: 'Description 1',
        image: 'https://basetop.ru/wp-content/uploads/2022/12/movies-2023-696x392.jpg',
        trailerLink: 'https://example.com/trailer1',
        thumbnail: 'https://example.com/thumbnail1.jpg',
        owner: 'user_id_1',
        movieId: 10,
        nameRU: 'Movie Name RU 1',
        nameEN: 'Movie Name EN 1',
      },
      {
        country: 'Country 1',
        director: 'Director 1',
        duration: 102,
        year: '2021',
        description: 'Description 1',
        image: 'https://basetop.ru/wp-content/uploads/2022/12/movies-2023-696x392.jpg',
        trailerLink: 'https://example.com/trailer1',
        thumbnail: 'https://example.com/thumbnail1.jpg',
        owner: 'user_id_1',
        movieId: 11,
        nameRU: 'Movie Name RU 1',
        nameEN: 'Movie Name EN 1',
      },
      {
        country: 'Country 1',
        director: 'Director 1',
        duration: 102,
        year: '2021',
        description: 'Description 1',
        image: 'https://basetop.ru/wp-content/uploads/2022/12/movies-2023-696x392.jpg',
        trailerLink: 'https://example.com/trailer1',
        thumbnail: 'https://example.com/thumbnail1.jpg',
        owner: 'user_id_1',
        movieId: 12,
        nameRU: 'Movie Name RU 1',
        nameEN: 'Movie Name EN 1',
      },
      {
        country: 'Country 1',
        director: 'Director 1',
        duration: 102,
        year: '2021',
        description: 'Description 1',
        image: 'https://basetop.ru/wp-content/uploads/2022/12/movies-2023-696x392.jpg',
        trailerLink: 'https://example.com/trailer1',
        thumbnail: 'https://example.com/thumbnail1.jpg',
        owner: 'user_id_1',
        movieId: 13,
        nameRU: 'Movie Name RU 1',
        nameEN: 'Movie Name EN 1',
      },
      {
        country: 'Country 1',
        director: 'Director 1',
        duration: 102,
        year: '2021',
        description: 'Description 1',
        image: 'https://basetop.ru/wp-content/uploads/2022/12/movies-2023-696x392.jpg',
        trailerLink: 'https://example.com/trailer1',
        thumbnail: 'https://example.com/thumbnail1.jpg',
        owner: 'user_id_1',
        movieId: 14,
        nameRU: 'Movie Name RU 1',
        nameEN: 'Movie Name EN 1',
      },
      {
        country: 'Country 1',
        director: 'Director 1',
        duration: 102,
        year: '2021',
        description: 'Description 1',
        image: 'https://basetop.ru/wp-content/uploads/2022/12/movies-2023-696x392.jpg',
        trailerLink: 'https://example.com/trailer1',
        thumbnail: 'https://example.com/thumbnail1.jpg',
        owner: 'user_id_1',
        movieId: 15,
        nameRU: 'Movie Name RU 1',
        nameEN: 'Movie Name EN 1',
      },
      {
        country: 'Country 1',
        director: 'Director 1',
        duration: 102,
        year: '2021',
        description: 'Description 1',
        image: 'https://basetop.ru/wp-content/uploads/2022/12/movies-2023-696x392.jpg',
        trailerLink: 'https://example.com/trailer1',
        thumbnail: 'https://example.com/thumbnail1.jpg',
        owner: 'user_id_1',
        movieId: 16,
        nameRU: 'Movie Name RU 1',
        nameEN: 'Movie Name EN 1',
      },
      {
        country: 'Country 1',
        director: 'Director 1',
        duration: 102,
        year: '2021',
        description: 'Description 1',
        image: 'https://basetop.ru/wp-content/uploads/2022/12/movies-2023-696x392.jpg',
        trailerLink: 'https://example.com/trailer1',
        thumbnail: 'https://example.com/thumbnail1.jpg',
        owner: 'user_id_1',
        movieId: 17,
        nameRU: '33 слова о дизайне',
        nameEN: 'Movie Name EN 1',
      },
      {
          country: 'Country 1',
          director: 'Director 1',
          duration: 102,
          year: '2021',
          description: 'Description 1',
          image: 'https://basetop.ru/wp-content/uploads/2022/12/movies-2023-696x392.jpg',
          trailerLink: 'https://example.com/trailer1',
          thumbnail: 'https://example.com/thumbnail1.jpg',
          owner: 'user_id_1',
          movieId: 18,
          nameRU: 'Киноальманах «100 лет дизайна»',
          nameEN: 'Movie Name EN 1',
        },
        {
          country: 'Country 1',
          director: 'Director 1',
          duration: 102,
          year: '2021',
          description: 'Description 1',
          image:  'https://basetop.ru/wp-content/uploads/2022/12/movies-2023-696x392.jpg',
          trailerLink: 'https://example.com/trailer1',
          thumbnail: 'https://example.com/thumbnail1.jpg',
          owner: 'user_id_1',
          movieId: 19,
          nameRU: 'В погоне за Бенкси',
          nameEN: 'Movie Name EN 1',
        },
        {
          country: 'Country 1',
          director: 'Director 1',
          duration: 102,
          year: '2021',
          description: 'Description 1',
          image: 'https://basetop.ru/wp-content/uploads/2022/05/2022-kino-filmy-.jpg',
          trailerLink: 'https://example.com/trailer1',
          thumbnail: 'https://example.com/thumbnail1.jpg',
          owner: 'user_id_1',
          movieId: 20,
          nameRU: 'Баския: Взрыв реальности',
          nameEN: 'Movie Name EN 1',
        },
  ];
  
  const savedMovies = [
    {
      country: 'Country 1',
      director: 'Director 1',
      duration: 102,
      year: '2021',
      description: 'Description 1',
      image: 'https://basetop.ru/wp-content/uploads/2022/12/movies-2023-696x392.jpg',
      trailerLink: 'https://example.com/trailer1',
      thumbnail: 'https://example.com/thumbnail1.jpg',
      owner: 'user_id_1',
      movieId: 2,
      nameRU: '33 слова о дизайне',
      nameEN: 'Movie Name EN 1',
    },
    {
        country: 'Country 1',
        director: 'Director 1',
        duration: 102,
        year: '2021',
        description: 'Description 1',
        image: 'https://basetop.ru/wp-content/uploads/2022/12/movies-2023-696x392.jpg',
        trailerLink: 'https://example.com/trailer1',
        thumbnail: 'https://example.com/thumbnail1.jpg',
        owner: 'user_id_1',
        movieId: 3,
        nameRU: 'Киноальманах «100 лет дизайна»',
        nameEN: 'Movie Name EN 1',
      },
      {
        country: 'Country 1',
        director: 'Director 1',
        duration: 102,
        year: '2021',
        description: 'Description 1',
        image:  'https://basetop.ru/wp-content/uploads/2022/12/movies-2023-696x392.jpg',
        trailerLink: 'https://example.com/trailer1',
        thumbnail: 'https://example.com/thumbnail1.jpg',
        owner: 'user_id_1',
        movieId: 4,
        nameRU: 'В погоне за Бенкси',
        nameEN: 'Movie Name EN 1',
      },  
  ];

const MOVIES_PER_PAGE_LARGE = 12;
const MOVIES_PER_PAGE_MIDDLE = 8;
const MOVIES_PER_PAGE_SMALL = 5;

export {
  MOVIES_PER_PAGE_LARGE,
  MOVIES_PER_PAGE_MIDDLE,
  MOVIES_PER_PAGE_SMALL,
  savedMovies,
  exampleMovies,
  STACK,
}